export const environment = {
  production: true,
  PROVIDER:'https://rpc-mumbai.maticvigil.com',
  CONTRACT_ADDRESS:'0x4eb8500e0ec8e16dfd7ec5dde239b2c10b024023',
  TOKENSALE_ADDRESS:'0xfe0af28cc19c1f4eb00f061df54adc725a3cdd4d',
  LOGO:'assets/images/logo.svg',
  TITLE:'Star Card Games',
  NETWORK:'MATIC',
  TYPE:'TESTNET',
  FROMTOKENNAME:'MATIC',
  TOTOKENNAME:'SCSG',
  TRANSLINK:'https://mumbai.polygonscan.com/tx/',
  SUPPORTMAIL:'contact@starcardsports.com',
  FACEBOOK:'',
  INSTAGRAM:'',
  PINTEREST:'',
  TWITTER:'',
  GOOGLE:'',
  WHATSAPP:'',
  LINKEDIN:'',
};
